//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.06 at 07:19:09 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = Links.ENTITY)
package ua.delivery.model;

import ua.delivery.service.Links;
